version: '3'

services:
  pg-mks:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pg-mks'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379   
volumes:
  pg-data: